### ISSUE TITLE
alphafold3 archive not saving metrics

### ISSUE THREAD

**Issue by isi1000** [flyark/AFM-LIS#3]
Hi! in the alphafold3 version of the notebook it calcules and plot the results perfectly but I can't get the raw results, so for example I am unable to see what is the LIA score, only the cLIA ones.
I don't know if it is my problem or a problem of the script; I am using alphafold3_lis_contact_v0.14.ipynb

Thank you in advance!

**Comment by flyark** [comment]
Hi, 

I've been thinking how to make the output csv with results instead of simply plotting. 

I am working on making new note that can make csv with all the results in addition to plotting the data. It seems working well but I need to check a little more. I will upload the updated note soon. 

Ah-Ram

**Comment by flyark** [comment]
Please check alphafold3_lis_contact_v0.15.ipynb and let me know whether it's working well.
