### ISSUE TITLE
PAE and distance filtering thresholds

### ISSUE THREAD

**Issue by Hrovatin** [flyark/AFM-LIS#8]
I wanted to use the LIS and cLIS metrics, however, I realized the default thresholds may not work for our data well.

There is much more uncertainty in our predictions, with cross-chain PAEs being very high (see plot below). I was wondering what would be your opinion on drastically increasing the PAE threshold so that LIS scores are not always 0. - Would the LIS scores still be meaningful if we changed the threshold to be much more permissive, thus discriminating between complexes?
PAE (y-axis) distributions for chain 1 to 2 and 2 to 1 (x-axis). The within-chain PAEs are much lower, as one would expect.
<img width="538" alt="image" src="https://github.com/user-attachments/assets/06a4d443-ab99-4dc7-8eaa-3126a6b6a88d">

Similarly goes for the distance threshold (I use distances between CA not CB atoms). - Do you think it would be appropriate to increase it from 8 to 9?

**Comment by flyark** [comment]
<img width="470" alt="image" src="https://github.com/user-attachments/assets/f32a4bbe-9091-41ab-88e6-8a67f2cbcb3b">

This is in the supplementary figure in my bioRxiv preprint.

Adjusting PAE may be helpful. In my testing set (fly and human PPI sets), I didn't see the noticeable difference when I tested all the PAE. I just picked up the best AUC-resulting PAE as a default. Some PPIs may be less stable, which can be reflected by relatively high PAE. 

In the same way to test all PAEs, I also tested different distances using Ca or Cb, which didn't show the noticeable difference among tested distances (7~12) when PAE 12 was fixed. But again, I selected **8** as a default distance to calculate cLIS since it resulted in the highest AUC in my tested PPI sets. And, **8** based on CB atoms has been used several times in other papers. If you want to use CA, you may need to increase the distance further. 

If your PPIs-of-interest are strong, you will see good scores regardless of PAE and distance. But if the interactions are weak/transient, you may see the variation of scores depending on your cutoff.

**Comment by Hrovatin** [comment]
Thank you very much for your advice. I will increase the thresholds as suggested.
